services:
    dimthi-web:
        build: .
        command: ["/usr/bin/supervisord"]
        container_name: dimthi-py
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
        ports:
            - "8368:8000"
        networks:
            - dimthi-net

networks:
    dimthi-net:
        driver: bridge
